// Code generated by protoc-gen-go.
// source: mdt_dialout.proto
// DO NOT EDIT!

/*
Package mdt_dialout is a generated protocol buffer package.

It is generated from these files:
	mdt_dialout.proto

It has these top-level messages:
	MdtDialoutArgs
*/
package mdt_dialout

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MdtDialoutArgs struct {
	ReqId  int64  `protobuf:"varint,1,opt,name=ReqId" json:"ReqId,omitempty"`
	Data   []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Errors string `protobuf:"bytes,3,opt,name=errors" json:"errors,omitempty"`
}

func (m *MdtDialoutArgs) Reset()                    { *m = MdtDialoutArgs{} }
func (m *MdtDialoutArgs) String() string            { return proto.CompactTextString(m) }
func (*MdtDialoutArgs) ProtoMessage()               {}
func (*MdtDialoutArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MdtDialoutArgs) GetReqId() int64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

func (m *MdtDialoutArgs) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *MdtDialoutArgs) GetErrors() string {
	if m != nil {
		return m.Errors
	}
	return ""
}

func init() {
	proto.RegisterType((*MdtDialoutArgs)(nil), "mdt_dialout.MdtDialoutArgs")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GRPCMdtDialout service

type GRPCMdtDialoutClient interface {
	MdtDialout(ctx context.Context, opts ...grpc.CallOption) (GRPCMdtDialout_MdtDialoutClient, error)
}

type gRPCMdtDialoutClient struct {
	cc *grpc.ClientConn
}

func NewGRPCMdtDialoutClient(cc *grpc.ClientConn) GRPCMdtDialoutClient {
	return &gRPCMdtDialoutClient{cc}
}

func (c *gRPCMdtDialoutClient) MdtDialout(ctx context.Context, opts ...grpc.CallOption) (GRPCMdtDialout_MdtDialoutClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GRPCMdtDialout_serviceDesc.Streams[0], c.cc, "/mdt_dialout.gRPCMdtDialout/MdtDialout", opts...)
	if err != nil {
		return nil, err
	}
	x := &gRPCMdtDialoutMdtDialoutClient{stream}
	return x, nil
}

type GRPCMdtDialout_MdtDialoutClient interface {
	Send(*MdtDialoutArgs) error
	Recv() (*MdtDialoutArgs, error)
	grpc.ClientStream
}

type gRPCMdtDialoutMdtDialoutClient struct {
	grpc.ClientStream
}

func (x *gRPCMdtDialoutMdtDialoutClient) Send(m *MdtDialoutArgs) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gRPCMdtDialoutMdtDialoutClient) Recv() (*MdtDialoutArgs, error) {
	m := new(MdtDialoutArgs)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for GRPCMdtDialout service

type GRPCMdtDialoutServer interface {
	MdtDialout(GRPCMdtDialout_MdtDialoutServer) error
}

func RegisterGRPCMdtDialoutServer(s *grpc.Server, srv GRPCMdtDialoutServer) {
	s.RegisterService(&_GRPCMdtDialout_serviceDesc, srv)
}

func _GRPCMdtDialout_MdtDialout_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GRPCMdtDialoutServer).MdtDialout(&gRPCMdtDialoutMdtDialoutServer{stream})
}

type GRPCMdtDialout_MdtDialoutServer interface {
	Send(*MdtDialoutArgs) error
	Recv() (*MdtDialoutArgs, error)
	grpc.ServerStream
}

type gRPCMdtDialoutMdtDialoutServer struct {
	grpc.ServerStream
}

func (x *gRPCMdtDialoutMdtDialoutServer) Send(m *MdtDialoutArgs) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gRPCMdtDialoutMdtDialoutServer) Recv() (*MdtDialoutArgs, error) {
	m := new(MdtDialoutArgs)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _GRPCMdtDialout_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mdt_dialout.gRPCMdtDialout",
	HandlerType: (*GRPCMdtDialoutServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MdtDialout",
			Handler:       _GRPCMdtDialout_MdtDialout_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "mdt_dialout.proto",
}

func init() { proto.RegisterFile("mdt_dialout.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 151 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcc, 0x4d, 0x29, 0x89,
	0x4f, 0xc9, 0x4c, 0xcc, 0xc9, 0x2f, 0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x46,
	0x12, 0x52, 0x0a, 0xe2, 0xe2, 0xf3, 0x4d, 0x29, 0x71, 0x81, 0xf0, 0x1c, 0x8b, 0xd2, 0x8b, 0x85,
	0x44, 0xb8, 0x58, 0x83, 0x52, 0x0b, 0x3d, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x98, 0x83, 0x20,
	0x1c, 0x21, 0x21, 0x2e, 0x96, 0x94, 0xc4, 0x92, 0x44, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x9e, 0x20,
	0x30, 0x5b, 0x48, 0x8c, 0x8b, 0x2d, 0xb5, 0xa8, 0x28, 0xbf, 0xa8, 0x58, 0x82, 0x59, 0x81, 0x51,
	0x83, 0x33, 0x08, 0xca, 0x33, 0x8a, 0xe3, 0xe2, 0x4b, 0x0f, 0x0a, 0x70, 0x46, 0x98, 0x2b, 0xe4,
	0xc3, 0xc5, 0x85, 0xc4, 0x93, 0xd6, 0x43, 0x76, 0x14, 0xaa, 0xf5, 0x52, 0xf8, 0x24, 0x95, 0x18,
	0x34, 0x18, 0x0d, 0x18, 0x93, 0xd8, 0xc0, 0xfe, 0x30, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xd9,
	0xe5, 0x52, 0x38, 0xdc, 0x00, 0x00, 0x00,
}
