// Code generated by protoc-gen-go.
// source: ems_grpc.proto
// DO NOT EDIT!

/*
Package IOSXRExtensibleManagabilityService is a generated protocol buffer package.

It is generated from these files:
	ems_grpc.proto

It has these top-level messages:
	ConfigGetArgs
	ConfigGetReply
	GetOperArgs
	GetOperReply
	ConfigArgs
	ConfigReply
	CliConfigArgs
	CliConfigReply
	CommitReplaceArgs
	CommitReplaceReply
	CommitMsg
	CommitArgs
	CommitReply
	DiscardChangesArgs
	DiscardChangesReply
	ShowCmdArgs
	ShowCmdTextReply
	ShowCmdJSONReply
	QOSMarking
	CreateSubsArgs
	ActionJSONArgs
	ActionJSONReply
	CreateSubsReply
	GetModelsInput
	GetModelsOutput
	GetProtoFileArgs
	GetProtoFileReply
*/
package IOSXRExtensibleManagabilityService

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CommitResult int32

const (
	CommitResult_CHANGE    CommitResult = 0
	CommitResult_NO_CHANGE CommitResult = 1
	CommitResult_FAIL      CommitResult = 2
)

var CommitResult_name = map[int32]string{
	0: "CHANGE",
	1: "NO_CHANGE",
	2: "FAIL",
}
var CommitResult_value = map[string]int32{
	"CHANGE":    0,
	"NO_CHANGE": 1,
	"FAIL":      2,
}

func (x CommitResult) String() string {
	return proto.EnumName(CommitResult_name, int32(x))
}
func (CommitResult) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type OC_RPC_RESPONSE_TYPE int32

const (
	OC_RPC_RESPONSE_TYPE_OK                      OC_RPC_RESPONSE_TYPE = 0
	OC_RPC_RESPONSE_TYPE_NOK                     OC_RPC_RESPONSE_TYPE = 1
	OC_RPC_RESPONSE_TYPE_UNSUPPORTED_PATH        OC_RPC_RESPONSE_TYPE = 2
	OC_RPC_RESPONSE_TYPE_INVALID_PATH            OC_RPC_RESPONSE_TYPE = 3
	OC_RPC_RESPONSE_TYPE_INVALID_CONFIGURATION   OC_RPC_RESPONSE_TYPE = 4
	OC_RPC_RESPONSE_TYPE_UNSUPPORTED_INTERVAL    OC_RPC_RESPONSE_TYPE = 5
	OC_RPC_RESPONSE_TYPE_UNSUPPORTED_ENCODING    OC_RPC_RESPONSE_TYPE = 6
	OC_RPC_RESPONSE_TYPE_INVALID_SUBSCRIPTION_ID OC_RPC_RESPONSE_TYPE = 7
)

var OC_RPC_RESPONSE_TYPE_name = map[int32]string{
	0: "OK",
	1: "NOK",
	2: "UNSUPPORTED_PATH",
	3: "INVALID_PATH",
	4: "INVALID_CONFIGURATION",
	5: "UNSUPPORTED_INTERVAL",
	6: "UNSUPPORTED_ENCODING",
	7: "INVALID_SUBSCRIPTION_ID",
}
var OC_RPC_RESPONSE_TYPE_value = map[string]int32{
	"OK":                      0,
	"NOK":                     1,
	"UNSUPPORTED_PATH":        2,
	"INVALID_PATH":            3,
	"INVALID_CONFIGURATION":   4,
	"UNSUPPORTED_INTERVAL":    5,
	"UNSUPPORTED_ENCODING":    6,
	"INVALID_SUBSCRIPTION_ID": 7,
}

func (x OC_RPC_RESPONSE_TYPE) String() string {
	return proto.EnumName(OC_RPC_RESPONSE_TYPE_name, int32(x))
}
func (OC_RPC_RESPONSE_TYPE) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type GET_MODEL_TYPE int32

const (
	GET_MODEL_TYPE_MODULE       GET_MODEL_TYPE = 0
	GET_MODEL_TYPE_AUGMENTATION GET_MODEL_TYPE = 1
	GET_MODEL_TYPE_DEVIATION    GET_MODEL_TYPE = 2
	GET_MODEL_TYPE_BUNDLE       GET_MODEL_TYPE = 3
)

var GET_MODEL_TYPE_name = map[int32]string{
	0: "MODULE",
	1: "AUGMENTATION",
	2: "DEVIATION",
	3: "BUNDLE",
}
var GET_MODEL_TYPE_value = map[string]int32{
	"MODULE":       0,
	"AUGMENTATION": 1,
	"DEVIATION":    2,
	"BUNDLE":       3,
}

func (x GET_MODEL_TYPE) String() string {
	return proto.EnumName(GET_MODEL_TYPE_name, int32(x))
}
func (GET_MODEL_TYPE) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type GetModelsInput_MODLE_REQUEST_TYPE int32

const (
	GetModelsInput_SUMMARY GetModelsInput_MODLE_REQUEST_TYPE = 0
	GetModelsInput_DETAIL  GetModelsInput_MODLE_REQUEST_TYPE = 1
)

var GetModelsInput_MODLE_REQUEST_TYPE_name = map[int32]string{
	0: "SUMMARY",
	1: "DETAIL",
}
var GetModelsInput_MODLE_REQUEST_TYPE_value = map[string]int32{
	"SUMMARY": 0,
	"DETAIL":  1,
}

func (x GetModelsInput_MODLE_REQUEST_TYPE) String() string {
	return proto.EnumName(GetModelsInput_MODLE_REQUEST_TYPE_name, int32(x))
}
func (GetModelsInput_MODLE_REQUEST_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{23, 0}
}

type ConfigGetArgs struct {
	ReqId        int64  `protobuf:"varint,1,opt,name=ReqId,json=reqId" json:"ReqId,omitempty"`
	Yangpathjson string `protobuf:"bytes,2,opt,name=yangpathjson" json:"yangpathjson,omitempty"`
}

func (m *ConfigGetArgs) Reset()                    { *m = ConfigGetArgs{} }
func (m *ConfigGetArgs) String() string            { return proto.CompactTextString(m) }
func (*ConfigGetArgs) ProtoMessage()               {}
func (*ConfigGetArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ConfigGetReply struct {
	ResReqId int64  `protobuf:"varint,1,opt,name=ResReqId,json=resReqId" json:"ResReqId,omitempty"`
	Yangjson string `protobuf:"bytes,2,opt,name=yangjson" json:"yangjson,omitempty"`
	Errors   string `protobuf:"bytes,3,opt,name=errors" json:"errors,omitempty"`
}

func (m *ConfigGetReply) Reset()                    { *m = ConfigGetReply{} }
func (m *ConfigGetReply) String() string            { return proto.CompactTextString(m) }
func (*ConfigGetReply) ProtoMessage()               {}
func (*ConfigGetReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type GetOperArgs struct {
	ReqId        int64  `protobuf:"varint,1,opt,name=ReqId,json=reqId" json:"ReqId,omitempty"`
	Yangpathjson string `protobuf:"bytes,2,opt,name=yangpathjson" json:"yangpathjson,omitempty"`
}

func (m *GetOperArgs) Reset()                    { *m = GetOperArgs{} }
func (m *GetOperArgs) String() string            { return proto.CompactTextString(m) }
func (*GetOperArgs) ProtoMessage()               {}
func (*GetOperArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type GetOperReply struct {
	ResReqId int64  `protobuf:"varint,1,opt,name=ResReqId,json=resReqId" json:"ResReqId,omitempty"`
	Yangjson string `protobuf:"bytes,2,opt,name=yangjson" json:"yangjson,omitempty"`
	Errors   string `protobuf:"bytes,3,opt,name=errors" json:"errors,omitempty"`
}

func (m *GetOperReply) Reset()                    { *m = GetOperReply{} }
func (m *GetOperReply) String() string            { return proto.CompactTextString(m) }
func (*GetOperReply) ProtoMessage()               {}
func (*GetOperReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ConfigArgs struct {
	ReqId          int64  `protobuf:"varint,1,opt,name=ReqId,json=reqId" json:"ReqId,omitempty"`
	Yangjson       string `protobuf:"bytes,2,opt,name=yangjson" json:"yangjson,omitempty"`
	Confirmed      bool   `protobuf:"varint,3,opt,name=Confirmed,json=confirmed" json:"Confirmed,omitempty"`
	ConfirmTimeout uint32 `protobuf:"varint,4,opt,name=ConfirmTimeout,json=confirmTimeout" json:"ConfirmTimeout,omitempty"`
}

func (m *ConfigArgs) Reset()                    { *m = ConfigArgs{} }
func (m *ConfigArgs) String() string            { return proto.CompactTextString(m) }
func (*ConfigArgs) ProtoMessage()               {}
func (*ConfigArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ConfigReply struct {
	ResReqId int64  `protobuf:"varint,1,opt,name=ResReqId,json=resReqId" json:"ResReqId,omitempty"`
	Errors   string `protobuf:"bytes,2,opt,name=errors" json:"errors,omitempty"`
	CommitID uint32 `protobuf:"varint,3,opt,name=CommitID,json=commitID" json:"CommitID,omitempty"`
}

func (m *ConfigReply) Reset()                    { *m = ConfigReply{} }
func (m *ConfigReply) String() string            { return proto.CompactTextString(m) }
func (*ConfigReply) ProtoMessage()               {}
func (*ConfigReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type CliConfigArgs struct {
	ReqId          int64  `protobuf:"varint,1,opt,name=ReqId,json=reqId" json:"ReqId,omitempty"`
	Cli            string `protobuf:"bytes,2,opt,name=cli" json:"cli,omitempty"`
	Confirmed      bool   `protobuf:"varint,3,opt,name=Confirmed,json=confirmed" json:"Confirmed,omitempty"`
	ConfirmTimeout uint32 `protobuf:"varint,4,opt,name=ConfirmTimeout,json=confirmTimeout" json:"ConfirmTimeout,omitempty"`
}

func (m *CliConfigArgs) Reset()                    { *m = CliConfigArgs{} }
func (m *CliConfigArgs) String() string            { return proto.CompactTextString(m) }
func (*CliConfigArgs) ProtoMessage()               {}
func (*CliConfigArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type CliConfigReply struct {
	ResReqId int64  `protobuf:"varint,1,opt,name=ResReqId,json=resReqId" json:"ResReqId,omitempty"`
	Errors   string `protobuf:"bytes,2,opt,name=errors" json:"errors,omitempty"`
	CommitID uint32 `protobuf:"varint,3,opt,name=CommitID,json=commitID" json:"CommitID,omitempty"`
}

func (m *CliConfigReply) Reset()                    { *m = CliConfigReply{} }
func (m *CliConfigReply) String() string            { return proto.CompactTextString(m) }
func (*CliConfigReply) ProtoMessage()               {}
func (*CliConfigReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type CommitReplaceArgs struct {
	ReqId    int64  `protobuf:"varint,1,opt,name=ReqId,json=reqId" json:"ReqId,omitempty"`
	Cli      string `protobuf:"bytes,2,opt,name=cli" json:"cli,omitempty"`
	Yangjson string `protobuf:"bytes,3,opt,name=yangjson" json:"yangjson,omitempty"`
}

func (m *CommitReplaceArgs) Reset()                    { *m = CommitReplaceArgs{} }
func (m *CommitReplaceArgs) String() string            { return proto.CompactTextString(m) }
func (*CommitReplaceArgs) ProtoMessage()               {}
func (*CommitReplaceArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type CommitReplaceReply struct {
	ResReqId int64  `protobuf:"varint,1,opt,name=ResReqId,json=resReqId" json:"ResReqId,omitempty"`
	Errors   string `protobuf:"bytes,2,opt,name=errors" json:"errors,omitempty"`
}

func (m *CommitReplaceReply) Reset()                    { *m = CommitReplaceReply{} }
func (m *CommitReplaceReply) String() string            { return proto.CompactTextString(m) }
func (*CommitReplaceReply) ProtoMessage()               {}
func (*CommitReplaceReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type CommitMsg struct {
	Label   string `protobuf:"bytes,1,opt,name=label" json:"label,omitempty"`
	Comment string `protobuf:"bytes,2,opt,name=comment" json:"comment,omitempty"`
}

func (m *CommitMsg) Reset()                    { *m = CommitMsg{} }
func (m *CommitMsg) String() string            { return proto.CompactTextString(m) }
func (*CommitMsg) ProtoMessage()               {}
func (*CommitMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type CommitArgs struct {
	ReqId    int64  `protobuf:"varint,1,opt,name=ReqId,json=reqId" json:"ReqId,omitempty"`
	CommitID uint32 `protobuf:"varint,2,opt,name=CommitID,json=commitID" json:"CommitID,omitempty"`
}

func (m *CommitArgs) Reset()                    { *m = CommitArgs{} }
func (m *CommitArgs) String() string            { return proto.CompactTextString(m) }
func (*CommitArgs) ProtoMessage()               {}
func (*CommitArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type CommitReply struct {
	ResReqId int64  `protobuf:"varint,1,opt,name=ResReqId,json=resReqId" json:"ResReqId,omitempty"`
	Errors   string `protobuf:"bytes,2,opt,name=errors" json:"errors,omitempty"`
}

func (m *CommitReply) Reset()                    { *m = CommitReply{} }
func (m *CommitReply) String() string            { return proto.CompactTextString(m) }
func (*CommitReply) ProtoMessage()               {}
func (*CommitReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type DiscardChangesArgs struct {
	ReqId int64 `protobuf:"varint,1,opt,name=ReqId,json=reqId" json:"ReqId,omitempty"`
}

func (m *DiscardChangesArgs) Reset()                    { *m = DiscardChangesArgs{} }
func (m *DiscardChangesArgs) String() string            { return proto.CompactTextString(m) }
func (*DiscardChangesArgs) ProtoMessage()               {}
func (*DiscardChangesArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type DiscardChangesReply struct {
	ResReqId int64  `protobuf:"varint,1,opt,name=ResReqId,json=resReqId" json:"ResReqId,omitempty"`
	Errors   string `protobuf:"bytes,2,opt,name=errors" json:"errors,omitempty"`
}

func (m *DiscardChangesReply) Reset()                    { *m = DiscardChangesReply{} }
func (m *DiscardChangesReply) String() string            { return proto.CompactTextString(m) }
func (*DiscardChangesReply) ProtoMessage()               {}
func (*DiscardChangesReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type ShowCmdArgs struct {
	ReqId int64  `protobuf:"varint,1,opt,name=ReqId,json=reqId" json:"ReqId,omitempty"`
	Cli   string `protobuf:"bytes,2,opt,name=cli" json:"cli,omitempty"`
}

func (m *ShowCmdArgs) Reset()                    { *m = ShowCmdArgs{} }
func (m *ShowCmdArgs) String() string            { return proto.CompactTextString(m) }
func (*ShowCmdArgs) ProtoMessage()               {}
func (*ShowCmdArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type ShowCmdTextReply struct {
	ResReqId int64  `protobuf:"varint,1,opt,name=ResReqId,json=resReqId" json:"ResReqId,omitempty"`
	Output   string `protobuf:"bytes,2,opt,name=output" json:"output,omitempty"`
	Errors   string `protobuf:"bytes,3,opt,name=errors" json:"errors,omitempty"`
}

func (m *ShowCmdTextReply) Reset()                    { *m = ShowCmdTextReply{} }
func (m *ShowCmdTextReply) String() string            { return proto.CompactTextString(m) }
func (*ShowCmdTextReply) ProtoMessage()               {}
func (*ShowCmdTextReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

type ShowCmdJSONReply struct {
	ResReqId   int64  `protobuf:"varint,1,opt,name=ResReqId,json=resReqId" json:"ResReqId,omitempty"`
	Jsonoutput string `protobuf:"bytes,2,opt,name=jsonoutput" json:"jsonoutput,omitempty"`
	Errors     string `protobuf:"bytes,3,opt,name=errors" json:"errors,omitempty"`
}

func (m *ShowCmdJSONReply) Reset()                    { *m = ShowCmdJSONReply{} }
func (m *ShowCmdJSONReply) String() string            { return proto.CompactTextString(m) }
func (*ShowCmdJSONReply) ProtoMessage()               {}
func (*ShowCmdJSONReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

// QOSMarking specifies the DSCP value to be set on transmitted telemetry
type QOSMarking struct {
	Marking uint32 `protobuf:"varint,1,opt,name=marking" json:"marking,omitempty"`
}

func (m *QOSMarking) Reset()                    { *m = QOSMarking{} }
func (m *QOSMarking) String() string            { return proto.CompactTextString(m) }
func (*QOSMarking) ProtoMessage()               {}
func (*QOSMarking) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

type CreateSubsArgs struct {
	ReqId         int64       `protobuf:"varint,1,opt,name=ReqId,json=reqId" json:"ReqId,omitempty"`
	Encode        int64       `protobuf:"varint,2,opt,name=encode" json:"encode,omitempty"`
	Subidstr      string      `protobuf:"bytes,3,opt,name=subidstr" json:"subidstr,omitempty"`
	Qos           *QOSMarking `protobuf:"bytes,4,opt,name=qos" json:"qos,omitempty"`
	Subscriptions []string    `protobuf:"bytes,5,rep,name=Subscriptions,json=subscriptions" json:"Subscriptions,omitempty"`
}

func (m *CreateSubsArgs) Reset()                    { *m = CreateSubsArgs{} }
func (m *CreateSubsArgs) String() string            { return proto.CompactTextString(m) }
func (*CreateSubsArgs) ProtoMessage()               {}
func (*CreateSubsArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *CreateSubsArgs) GetQos() *QOSMarking {
	if m != nil {
		return m.Qos
	}
	return nil
}

type ActionJSONArgs struct {
	ReqId        int64  `protobuf:"varint,1,opt,name=ReqId,json=reqId" json:"ReqId,omitempty"`
	Yangpathjson string `protobuf:"bytes,2,opt,name=yangpathjson" json:"yangpathjson,omitempty"`
}

func (m *ActionJSONArgs) Reset()                    { *m = ActionJSONArgs{} }
func (m *ActionJSONArgs) String() string            { return proto.CompactTextString(m) }
func (*ActionJSONArgs) ProtoMessage()               {}
func (*ActionJSONArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

type ActionJSONReply struct {
	ResReqId int64  `protobuf:"varint,1,opt,name=ResReqId,json=resReqId" json:"ResReqId,omitempty"`
	Yangjson string `protobuf:"bytes,2,opt,name=yangjson" json:"yangjson,omitempty"`
	Errors   string `protobuf:"bytes,3,opt,name=errors" json:"errors,omitempty"`
}

func (m *ActionJSONReply) Reset()                    { *m = ActionJSONReply{} }
func (m *ActionJSONReply) String() string            { return proto.CompactTextString(m) }
func (*ActionJSONReply) ProtoMessage()               {}
func (*ActionJSONReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

type CreateSubsReply struct {
	ResReqId int64  `protobuf:"varint,1,opt,name=ResReqId,json=resReqId" json:"ResReqId,omitempty"`
	Data     []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Errors   string `protobuf:"bytes,3,opt,name=errors" json:"errors,omitempty"`
}

func (m *CreateSubsReply) Reset()                    { *m = CreateSubsReply{} }
func (m *CreateSubsReply) String() string            { return proto.CompactTextString(m) }
func (*CreateSubsReply) ProtoMessage()               {}
func (*CreateSubsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

type GetModelsInput struct {
	RequestId   uint64                            `protobuf:"varint,1,opt,name=requestId" json:"requestId,omitempty"`
	Name        string                            `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Namespace   string                            `protobuf:"bytes,3,opt,name=namespace" json:"namespace,omitempty"`
	Version     string                            `protobuf:"bytes,4,opt,name=version" json:"version,omitempty"`
	RequestType GetModelsInput_MODLE_REQUEST_TYPE `protobuf:"varint,5,opt,name=requestType,enum=IOSXRExtensibleManagabilityService.GetModelsInput_MODLE_REQUEST_TYPE" json:"requestType,omitempty"`
}

func (m *GetModelsInput) Reset()                    { *m = GetModelsInput{} }
func (m *GetModelsInput) String() string            { return proto.CompactTextString(m) }
func (*GetModelsInput) ProtoMessage()               {}
func (*GetModelsInput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

type GetModelsOutput struct {
	RequestId    uint64                       `protobuf:"varint,1,opt,name=requestId" json:"requestId,omitempty"`
	Models       []*GetModelsOutput_ModelInfo `protobuf:"bytes,2,rep,name=models" json:"models,omitempty"`
	ResponseCode OC_RPC_RESPONSE_TYPE         `protobuf:"varint,3,opt,name=responseCode,enum=IOSXRExtensibleManagabilityService.OC_RPC_RESPONSE_TYPE" json:"responseCode,omitempty"`
	Msg          string                       `protobuf:"bytes,4,opt,name=msg" json:"msg,omitempty"`
}

func (m *GetModelsOutput) Reset()                    { *m = GetModelsOutput{} }
func (m *GetModelsOutput) String() string            { return proto.CompactTextString(m) }
func (*GetModelsOutput) ProtoMessage()               {}
func (*GetModelsOutput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *GetModelsOutput) GetModels() []*GetModelsOutput_ModelInfo {
	if m != nil {
		return m.Models
	}
	return nil
}

type GetModelsOutput_ModelInfo struct {
	Name      string         `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Namespace string         `protobuf:"bytes,2,opt,name=namespace" json:"namespace,omitempty"`
	Version   string         `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
	ModelType GET_MODEL_TYPE `protobuf:"varint,4,opt,name=modelType,enum=IOSXRExtensibleManagabilityService.GET_MODEL_TYPE" json:"modelType,omitempty"`
	ModelData string         `protobuf:"bytes,5,opt,name=modelData" json:"modelData,omitempty"`
}

func (m *GetModelsOutput_ModelInfo) Reset()                    { *m = GetModelsOutput_ModelInfo{} }
func (m *GetModelsOutput_ModelInfo) String() string            { return proto.CompactTextString(m) }
func (*GetModelsOutput_ModelInfo) ProtoMessage()               {}
func (*GetModelsOutput_ModelInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24, 0} }

type GetProtoFileArgs struct {
	ReqId    int64  `protobuf:"varint,1,opt,name=reqId" json:"reqId,omitempty"`
	YangPath string `protobuf:"bytes,2,opt,name=yangPath" json:"yangPath,omitempty"`
}

func (m *GetProtoFileArgs) Reset()                    { *m = GetProtoFileArgs{} }
func (m *GetProtoFileArgs) String() string            { return proto.CompactTextString(m) }
func (*GetProtoFileArgs) ProtoMessage()               {}
func (*GetProtoFileArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

type GetProtoFileReply struct {
	ReqId        int64  `protobuf:"varint,1,opt,name=reqId" json:"reqId,omitempty"`
	ProtoContent string `protobuf:"bytes,2,opt,name=protoContent" json:"protoContent,omitempty"`
	Errors       string `protobuf:"bytes,3,opt,name=errors" json:"errors,omitempty"`
}

func (m *GetProtoFileReply) Reset()                    { *m = GetProtoFileReply{} }
func (m *GetProtoFileReply) String() string            { return proto.CompactTextString(m) }
func (*GetProtoFileReply) ProtoMessage()               {}
func (*GetProtoFileReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func init() {
	proto.RegisterType((*ConfigGetArgs)(nil), "IOSXRExtensibleManagabilityService.ConfigGetArgs")
	proto.RegisterType((*ConfigGetReply)(nil), "IOSXRExtensibleManagabilityService.ConfigGetReply")
	proto.RegisterType((*GetOperArgs)(nil), "IOSXRExtensibleManagabilityService.GetOperArgs")
	proto.RegisterType((*GetOperReply)(nil), "IOSXRExtensibleManagabilityService.GetOperReply")
	proto.RegisterType((*ConfigArgs)(nil), "IOSXRExtensibleManagabilityService.ConfigArgs")
	proto.RegisterType((*ConfigReply)(nil), "IOSXRExtensibleManagabilityService.ConfigReply")
	proto.RegisterType((*CliConfigArgs)(nil), "IOSXRExtensibleManagabilityService.CliConfigArgs")
	proto.RegisterType((*CliConfigReply)(nil), "IOSXRExtensibleManagabilityService.CliConfigReply")
	proto.RegisterType((*CommitReplaceArgs)(nil), "IOSXRExtensibleManagabilityService.CommitReplaceArgs")
	proto.RegisterType((*CommitReplaceReply)(nil), "IOSXRExtensibleManagabilityService.CommitReplaceReply")
	proto.RegisterType((*CommitMsg)(nil), "IOSXRExtensibleManagabilityService.CommitMsg")
	proto.RegisterType((*CommitArgs)(nil), "IOSXRExtensibleManagabilityService.CommitArgs")
	proto.RegisterType((*CommitReply)(nil), "IOSXRExtensibleManagabilityService.CommitReply")
	proto.RegisterType((*DiscardChangesArgs)(nil), "IOSXRExtensibleManagabilityService.DiscardChangesArgs")
	proto.RegisterType((*DiscardChangesReply)(nil), "IOSXRExtensibleManagabilityService.DiscardChangesReply")
	proto.RegisterType((*ShowCmdArgs)(nil), "IOSXRExtensibleManagabilityService.ShowCmdArgs")
	proto.RegisterType((*ShowCmdTextReply)(nil), "IOSXRExtensibleManagabilityService.ShowCmdTextReply")
	proto.RegisterType((*ShowCmdJSONReply)(nil), "IOSXRExtensibleManagabilityService.ShowCmdJSONReply")
	proto.RegisterType((*QOSMarking)(nil), "IOSXRExtensibleManagabilityService.QOSMarking")
	proto.RegisterType((*CreateSubsArgs)(nil), "IOSXRExtensibleManagabilityService.CreateSubsArgs")
	proto.RegisterType((*ActionJSONArgs)(nil), "IOSXRExtensibleManagabilityService.ActionJSONArgs")
	proto.RegisterType((*ActionJSONReply)(nil), "IOSXRExtensibleManagabilityService.ActionJSONReply")
	proto.RegisterType((*CreateSubsReply)(nil), "IOSXRExtensibleManagabilityService.CreateSubsReply")
	proto.RegisterType((*GetModelsInput)(nil), "IOSXRExtensibleManagabilityService.GetModelsInput")
	proto.RegisterType((*GetModelsOutput)(nil), "IOSXRExtensibleManagabilityService.GetModelsOutput")
	proto.RegisterType((*GetModelsOutput_ModelInfo)(nil), "IOSXRExtensibleManagabilityService.GetModelsOutput.ModelInfo")
	proto.RegisterType((*GetProtoFileArgs)(nil), "IOSXRExtensibleManagabilityService.GetProtoFileArgs")
	proto.RegisterType((*GetProtoFileReply)(nil), "IOSXRExtensibleManagabilityService.GetProtoFileReply")
	proto.RegisterEnum("IOSXRExtensibleManagabilityService.CommitResult", CommitResult_name, CommitResult_value)
	proto.RegisterEnum("IOSXRExtensibleManagabilityService.OC_RPC_RESPONSE_TYPE", OC_RPC_RESPONSE_TYPE_name, OC_RPC_RESPONSE_TYPE_value)
	proto.RegisterEnum("IOSXRExtensibleManagabilityService.GET_MODEL_TYPE", GET_MODEL_TYPE_name, GET_MODEL_TYPE_value)
	proto.RegisterEnum("IOSXRExtensibleManagabilityService.GetModelsInput_MODLE_REQUEST_TYPE", GetModelsInput_MODLE_REQUEST_TYPE_name, GetModelsInput_MODLE_REQUEST_TYPE_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for GRPCConfigOper service

type GRPCConfigOperClient interface {
	GetConfig(ctx context.Context, in *ConfigGetArgs, opts ...grpc.CallOption) (GRPCConfigOper_GetConfigClient, error)
	MergeConfig(ctx context.Context, in *ConfigArgs, opts ...grpc.CallOption) (*ConfigReply, error)
	DeleteConfig(ctx context.Context, in *ConfigArgs, opts ...grpc.CallOption) (*ConfigReply, error)
	RemoveConfig(ctx context.Context, in *ConfigArgs, opts ...grpc.CallOption) (*ConfigReply, error)
	ReplaceConfig(ctx context.Context, in *ConfigArgs, opts ...grpc.CallOption) (*ConfigReply, error)
	CliConfig(ctx context.Context, in *CliConfigArgs, opts ...grpc.CallOption) (*CliConfigReply, error)
	CommitReplace(ctx context.Context, in *CommitReplaceArgs, opts ...grpc.CallOption) (*CommitReplaceReply, error)
	// Do we need implicit or explicit commit
	//
	CommitConfig(ctx context.Context, in *CommitArgs, opts ...grpc.CallOption) (*CommitReply, error)
	ConfigDiscardChanges(ctx context.Context, in *DiscardChangesArgs, opts ...grpc.CallOption) (*DiscardChangesReply, error)
	// Get only returns oper data
	//
	GetOper(ctx context.Context, in *GetOperArgs, opts ...grpc.CallOption) (GRPCConfigOper_GetOperClient, error)
	// Get Telemetry Data
	CreateSubs(ctx context.Context, in *CreateSubsArgs, opts ...grpc.CallOption) (GRPCConfigOper_CreateSubsClient, error)
	// Get Proto File
	GetProtoFile(ctx context.Context, in *GetProtoFileArgs, opts ...grpc.CallOption) (GRPCConfigOper_GetProtoFileClient, error)
}

type gRPCConfigOperClient struct {
	cc *grpc.ClientConn
}

func NewGRPCConfigOperClient(cc *grpc.ClientConn) GRPCConfigOperClient {
	return &gRPCConfigOperClient{cc}
}

func (c *gRPCConfigOperClient) GetConfig(ctx context.Context, in *ConfigGetArgs, opts ...grpc.CallOption) (GRPCConfigOper_GetConfigClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GRPCConfigOper_serviceDesc.Streams[0], c.cc, "/IOSXRExtensibleManagabilityService.gRPCConfigOper/GetConfig", opts...)
	if err != nil {
		return nil, err
	}
	x := &gRPCConfigOperGetConfigClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GRPCConfigOper_GetConfigClient interface {
	Recv() (*ConfigGetReply, error)
	grpc.ClientStream
}

type gRPCConfigOperGetConfigClient struct {
	grpc.ClientStream
}

func (x *gRPCConfigOperGetConfigClient) Recv() (*ConfigGetReply, error) {
	m := new(ConfigGetReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gRPCConfigOperClient) MergeConfig(ctx context.Context, in *ConfigArgs, opts ...grpc.CallOption) (*ConfigReply, error) {
	out := new(ConfigReply)
	err := grpc.Invoke(ctx, "/IOSXRExtensibleManagabilityService.gRPCConfigOper/MergeConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPCConfigOperClient) DeleteConfig(ctx context.Context, in *ConfigArgs, opts ...grpc.CallOption) (*ConfigReply, error) {
	out := new(ConfigReply)
	err := grpc.Invoke(ctx, "/IOSXRExtensibleManagabilityService.gRPCConfigOper/DeleteConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPCConfigOperClient) RemoveConfig(ctx context.Context, in *ConfigArgs, opts ...grpc.CallOption) (*ConfigReply, error) {
	out := new(ConfigReply)
	err := grpc.Invoke(ctx, "/IOSXRExtensibleManagabilityService.gRPCConfigOper/RemoveConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPCConfigOperClient) ReplaceConfig(ctx context.Context, in *ConfigArgs, opts ...grpc.CallOption) (*ConfigReply, error) {
	out := new(ConfigReply)
	err := grpc.Invoke(ctx, "/IOSXRExtensibleManagabilityService.gRPCConfigOper/ReplaceConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPCConfigOperClient) CliConfig(ctx context.Context, in *CliConfigArgs, opts ...grpc.CallOption) (*CliConfigReply, error) {
	out := new(CliConfigReply)
	err := grpc.Invoke(ctx, "/IOSXRExtensibleManagabilityService.gRPCConfigOper/CliConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPCConfigOperClient) CommitReplace(ctx context.Context, in *CommitReplaceArgs, opts ...grpc.CallOption) (*CommitReplaceReply, error) {
	out := new(CommitReplaceReply)
	err := grpc.Invoke(ctx, "/IOSXRExtensibleManagabilityService.gRPCConfigOper/CommitReplace", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPCConfigOperClient) CommitConfig(ctx context.Context, in *CommitArgs, opts ...grpc.CallOption) (*CommitReply, error) {
	out := new(CommitReply)
	err := grpc.Invoke(ctx, "/IOSXRExtensibleManagabilityService.gRPCConfigOper/CommitConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPCConfigOperClient) ConfigDiscardChanges(ctx context.Context, in *DiscardChangesArgs, opts ...grpc.CallOption) (*DiscardChangesReply, error) {
	out := new(DiscardChangesReply)
	err := grpc.Invoke(ctx, "/IOSXRExtensibleManagabilityService.gRPCConfigOper/ConfigDiscardChanges", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPCConfigOperClient) GetOper(ctx context.Context, in *GetOperArgs, opts ...grpc.CallOption) (GRPCConfigOper_GetOperClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GRPCConfigOper_serviceDesc.Streams[1], c.cc, "/IOSXRExtensibleManagabilityService.gRPCConfigOper/GetOper", opts...)
	if err != nil {
		return nil, err
	}
	x := &gRPCConfigOperGetOperClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GRPCConfigOper_GetOperClient interface {
	Recv() (*GetOperReply, error)
	grpc.ClientStream
}

type gRPCConfigOperGetOperClient struct {
	grpc.ClientStream
}

func (x *gRPCConfigOperGetOperClient) Recv() (*GetOperReply, error) {
	m := new(GetOperReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gRPCConfigOperClient) CreateSubs(ctx context.Context, in *CreateSubsArgs, opts ...grpc.CallOption) (GRPCConfigOper_CreateSubsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GRPCConfigOper_serviceDesc.Streams[2], c.cc, "/IOSXRExtensibleManagabilityService.gRPCConfigOper/CreateSubs", opts...)
	if err != nil {
		return nil, err
	}
	x := &gRPCConfigOperCreateSubsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GRPCConfigOper_CreateSubsClient interface {
	Recv() (*CreateSubsReply, error)
	grpc.ClientStream
}

type gRPCConfigOperCreateSubsClient struct {
	grpc.ClientStream
}

func (x *gRPCConfigOperCreateSubsClient) Recv() (*CreateSubsReply, error) {
	m := new(CreateSubsReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gRPCConfigOperClient) GetProtoFile(ctx context.Context, in *GetProtoFileArgs, opts ...grpc.CallOption) (GRPCConfigOper_GetProtoFileClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GRPCConfigOper_serviceDesc.Streams[3], c.cc, "/IOSXRExtensibleManagabilityService.gRPCConfigOper/GetProtoFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &gRPCConfigOperGetProtoFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GRPCConfigOper_GetProtoFileClient interface {
	Recv() (*GetProtoFileReply, error)
	grpc.ClientStream
}

type gRPCConfigOperGetProtoFileClient struct {
	grpc.ClientStream
}

func (x *gRPCConfigOperGetProtoFileClient) Recv() (*GetProtoFileReply, error) {
	m := new(GetProtoFileReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for GRPCConfigOper service

type GRPCConfigOperServer interface {
	GetConfig(*ConfigGetArgs, GRPCConfigOper_GetConfigServer) error
	MergeConfig(context.Context, *ConfigArgs) (*ConfigReply, error)
	DeleteConfig(context.Context, *ConfigArgs) (*ConfigReply, error)
	RemoveConfig(context.Context, *ConfigArgs) (*ConfigReply, error)
	ReplaceConfig(context.Context, *ConfigArgs) (*ConfigReply, error)
	CliConfig(context.Context, *CliConfigArgs) (*CliConfigReply, error)
	CommitReplace(context.Context, *CommitReplaceArgs) (*CommitReplaceReply, error)
	// Do we need implicit or explicit commit
	//
	CommitConfig(context.Context, *CommitArgs) (*CommitReply, error)
	ConfigDiscardChanges(context.Context, *DiscardChangesArgs) (*DiscardChangesReply, error)
	// Get only returns oper data
	//
	GetOper(*GetOperArgs, GRPCConfigOper_GetOperServer) error
	// Get Telemetry Data
	CreateSubs(*CreateSubsArgs, GRPCConfigOper_CreateSubsServer) error
	// Get Proto File
	GetProtoFile(*GetProtoFileArgs, GRPCConfigOper_GetProtoFileServer) error
}

func RegisterGRPCConfigOperServer(s *grpc.Server, srv GRPCConfigOperServer) {
	s.RegisterService(&_GRPCConfigOper_serviceDesc, srv)
}

func _GRPCConfigOper_GetConfig_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConfigGetArgs)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GRPCConfigOperServer).GetConfig(m, &gRPCConfigOperGetConfigServer{stream})
}

type GRPCConfigOper_GetConfigServer interface {
	Send(*ConfigGetReply) error
	grpc.ServerStream
}

type gRPCConfigOperGetConfigServer struct {
	grpc.ServerStream
}

func (x *gRPCConfigOperGetConfigServer) Send(m *ConfigGetReply) error {
	return x.ServerStream.SendMsg(m)
}

func _GRPCConfigOper_MergeConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCConfigOperServer).MergeConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IOSXRExtensibleManagabilityService.gRPCConfigOper/MergeConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCConfigOperServer).MergeConfig(ctx, req.(*ConfigArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPCConfigOper_DeleteConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCConfigOperServer).DeleteConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IOSXRExtensibleManagabilityService.gRPCConfigOper/DeleteConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCConfigOperServer).DeleteConfig(ctx, req.(*ConfigArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPCConfigOper_RemoveConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCConfigOperServer).RemoveConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IOSXRExtensibleManagabilityService.gRPCConfigOper/RemoveConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCConfigOperServer).RemoveConfig(ctx, req.(*ConfigArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPCConfigOper_ReplaceConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCConfigOperServer).ReplaceConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IOSXRExtensibleManagabilityService.gRPCConfigOper/ReplaceConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCConfigOperServer).ReplaceConfig(ctx, req.(*ConfigArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPCConfigOper_CliConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CliConfigArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCConfigOperServer).CliConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IOSXRExtensibleManagabilityService.gRPCConfigOper/CliConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCConfigOperServer).CliConfig(ctx, req.(*CliConfigArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPCConfigOper_CommitReplace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitReplaceArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCConfigOperServer).CommitReplace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IOSXRExtensibleManagabilityService.gRPCConfigOper/CommitReplace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCConfigOperServer).CommitReplace(ctx, req.(*CommitReplaceArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPCConfigOper_CommitConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCConfigOperServer).CommitConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IOSXRExtensibleManagabilityService.gRPCConfigOper/CommitConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCConfigOperServer).CommitConfig(ctx, req.(*CommitArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPCConfigOper_ConfigDiscardChanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscardChangesArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCConfigOperServer).ConfigDiscardChanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IOSXRExtensibleManagabilityService.gRPCConfigOper/ConfigDiscardChanges",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCConfigOperServer).ConfigDiscardChanges(ctx, req.(*DiscardChangesArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPCConfigOper_GetOper_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetOperArgs)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GRPCConfigOperServer).GetOper(m, &gRPCConfigOperGetOperServer{stream})
}

type GRPCConfigOper_GetOperServer interface {
	Send(*GetOperReply) error
	grpc.ServerStream
}

type gRPCConfigOperGetOperServer struct {
	grpc.ServerStream
}

func (x *gRPCConfigOperGetOperServer) Send(m *GetOperReply) error {
	return x.ServerStream.SendMsg(m)
}

func _GRPCConfigOper_CreateSubs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CreateSubsArgs)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GRPCConfigOperServer).CreateSubs(m, &gRPCConfigOperCreateSubsServer{stream})
}

type GRPCConfigOper_CreateSubsServer interface {
	Send(*CreateSubsReply) error
	grpc.ServerStream
}

type gRPCConfigOperCreateSubsServer struct {
	grpc.ServerStream
}

func (x *gRPCConfigOperCreateSubsServer) Send(m *CreateSubsReply) error {
	return x.ServerStream.SendMsg(m)
}

func _GRPCConfigOper_GetProtoFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetProtoFileArgs)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GRPCConfigOperServer).GetProtoFile(m, &gRPCConfigOperGetProtoFileServer{stream})
}

type GRPCConfigOper_GetProtoFileServer interface {
	Send(*GetProtoFileReply) error
	grpc.ServerStream
}

type gRPCConfigOperGetProtoFileServer struct {
	grpc.ServerStream
}

func (x *gRPCConfigOperGetProtoFileServer) Send(m *GetProtoFileReply) error {
	return x.ServerStream.SendMsg(m)
}

var _GRPCConfigOper_serviceDesc = grpc.ServiceDesc{
	ServiceName: "IOSXRExtensibleManagabilityService.gRPCConfigOper",
	HandlerType: (*GRPCConfigOperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MergeConfig",
			Handler:    _GRPCConfigOper_MergeConfig_Handler,
		},
		{
			MethodName: "DeleteConfig",
			Handler:    _GRPCConfigOper_DeleteConfig_Handler,
		},
		{
			MethodName: "RemoveConfig",
			Handler:    _GRPCConfigOper_RemoveConfig_Handler,
		},
		{
			MethodName: "ReplaceConfig",
			Handler:    _GRPCConfigOper_ReplaceConfig_Handler,
		},
		{
			MethodName: "CliConfig",
			Handler:    _GRPCConfigOper_CliConfig_Handler,
		},
		{
			MethodName: "CommitReplace",
			Handler:    _GRPCConfigOper_CommitReplace_Handler,
		},
		{
			MethodName: "CommitConfig",
			Handler:    _GRPCConfigOper_CommitConfig_Handler,
		},
		{
			MethodName: "ConfigDiscardChanges",
			Handler:    _GRPCConfigOper_ConfigDiscardChanges_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetConfig",
			Handler:       _GRPCConfigOper_GetConfig_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetOper",
			Handler:       _GRPCConfigOper_GetOper_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CreateSubs",
			Handler:       _GRPCConfigOper_CreateSubs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetProtoFile",
			Handler:       _GRPCConfigOper_GetProtoFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: fileDescriptor0,
}

// Client API for GRPCExec service

type GRPCExecClient interface {
	// Exec commands
	ShowCmdTextOutput(ctx context.Context, in *ShowCmdArgs, opts ...grpc.CallOption) (GRPCExec_ShowCmdTextOutputClient, error)
	ShowCmdJSONOutput(ctx context.Context, in *ShowCmdArgs, opts ...grpc.CallOption) (GRPCExec_ShowCmdJSONOutputClient, error)
	ActionJSON(ctx context.Context, in *ActionJSONArgs, opts ...grpc.CallOption) (GRPCExec_ActionJSONClient, error)
}

type gRPCExecClient struct {
	cc *grpc.ClientConn
}

func NewGRPCExecClient(cc *grpc.ClientConn) GRPCExecClient {
	return &gRPCExecClient{cc}
}

func (c *gRPCExecClient) ShowCmdTextOutput(ctx context.Context, in *ShowCmdArgs, opts ...grpc.CallOption) (GRPCExec_ShowCmdTextOutputClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GRPCExec_serviceDesc.Streams[0], c.cc, "/IOSXRExtensibleManagabilityService.gRPCExec/ShowCmdTextOutput", opts...)
	if err != nil {
		return nil, err
	}
	x := &gRPCExecShowCmdTextOutputClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GRPCExec_ShowCmdTextOutputClient interface {
	Recv() (*ShowCmdTextReply, error)
	grpc.ClientStream
}

type gRPCExecShowCmdTextOutputClient struct {
	grpc.ClientStream
}

func (x *gRPCExecShowCmdTextOutputClient) Recv() (*ShowCmdTextReply, error) {
	m := new(ShowCmdTextReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gRPCExecClient) ShowCmdJSONOutput(ctx context.Context, in *ShowCmdArgs, opts ...grpc.CallOption) (GRPCExec_ShowCmdJSONOutputClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GRPCExec_serviceDesc.Streams[1], c.cc, "/IOSXRExtensibleManagabilityService.gRPCExec/ShowCmdJSONOutput", opts...)
	if err != nil {
		return nil, err
	}
	x := &gRPCExecShowCmdJSONOutputClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GRPCExec_ShowCmdJSONOutputClient interface {
	Recv() (*ShowCmdJSONReply, error)
	grpc.ClientStream
}

type gRPCExecShowCmdJSONOutputClient struct {
	grpc.ClientStream
}

func (x *gRPCExecShowCmdJSONOutputClient) Recv() (*ShowCmdJSONReply, error) {
	m := new(ShowCmdJSONReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gRPCExecClient) ActionJSON(ctx context.Context, in *ActionJSONArgs, opts ...grpc.CallOption) (GRPCExec_ActionJSONClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GRPCExec_serviceDesc.Streams[2], c.cc, "/IOSXRExtensibleManagabilityService.gRPCExec/ActionJSON", opts...)
	if err != nil {
		return nil, err
	}
	x := &gRPCExecActionJSONClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GRPCExec_ActionJSONClient interface {
	Recv() (*ActionJSONReply, error)
	grpc.ClientStream
}

type gRPCExecActionJSONClient struct {
	grpc.ClientStream
}

func (x *gRPCExecActionJSONClient) Recv() (*ActionJSONReply, error) {
	m := new(ActionJSONReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for GRPCExec service

type GRPCExecServer interface {
	// Exec commands
	ShowCmdTextOutput(*ShowCmdArgs, GRPCExec_ShowCmdTextOutputServer) error
	ShowCmdJSONOutput(*ShowCmdArgs, GRPCExec_ShowCmdJSONOutputServer) error
	ActionJSON(*ActionJSONArgs, GRPCExec_ActionJSONServer) error
}

func RegisterGRPCExecServer(s *grpc.Server, srv GRPCExecServer) {
	s.RegisterService(&_GRPCExec_serviceDesc, srv)
}

func _GRPCExec_ShowCmdTextOutput_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ShowCmdArgs)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GRPCExecServer).ShowCmdTextOutput(m, &gRPCExecShowCmdTextOutputServer{stream})
}

type GRPCExec_ShowCmdTextOutputServer interface {
	Send(*ShowCmdTextReply) error
	grpc.ServerStream
}

type gRPCExecShowCmdTextOutputServer struct {
	grpc.ServerStream
}

func (x *gRPCExecShowCmdTextOutputServer) Send(m *ShowCmdTextReply) error {
	return x.ServerStream.SendMsg(m)
}

func _GRPCExec_ShowCmdJSONOutput_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ShowCmdArgs)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GRPCExecServer).ShowCmdJSONOutput(m, &gRPCExecShowCmdJSONOutputServer{stream})
}

type GRPCExec_ShowCmdJSONOutputServer interface {
	Send(*ShowCmdJSONReply) error
	grpc.ServerStream
}

type gRPCExecShowCmdJSONOutputServer struct {
	grpc.ServerStream
}

func (x *gRPCExecShowCmdJSONOutputServer) Send(m *ShowCmdJSONReply) error {
	return x.ServerStream.SendMsg(m)
}

func _GRPCExec_ActionJSON_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ActionJSONArgs)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GRPCExecServer).ActionJSON(m, &gRPCExecActionJSONServer{stream})
}

type GRPCExec_ActionJSONServer interface {
	Send(*ActionJSONReply) error
	grpc.ServerStream
}

type gRPCExecActionJSONServer struct {
	grpc.ServerStream
}

func (x *gRPCExecActionJSONServer) Send(m *ActionJSONReply) error {
	return x.ServerStream.SendMsg(m)
}

var _GRPCExec_serviceDesc = grpc.ServiceDesc{
	ServiceName: "IOSXRExtensibleManagabilityService.gRPCExec",
	HandlerType: (*GRPCExecServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ShowCmdTextOutput",
			Handler:       _GRPCExec_ShowCmdTextOutput_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ShowCmdJSONOutput",
			Handler:       _GRPCExec_ShowCmdJSONOutput_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ActionJSON",
			Handler:       _GRPCExec_ActionJSON_Handler,
			ServerStreams: true,
		},
	},
	Metadata: fileDescriptor0,
}

// Client API for OpenConfiggRPC service

type OpenConfiggRPCClient interface {
	// get-models rpc implementation per
	// github.com/openconfig/public/blob/master/release/models/rpc/openconfig-rpc.yang
	GetModels(ctx context.Context, in *GetModelsInput, opts ...grpc.CallOption) (*GetModelsOutput, error)
}

type openConfiggRPCClient struct {
	cc *grpc.ClientConn
}

func NewOpenConfiggRPCClient(cc *grpc.ClientConn) OpenConfiggRPCClient {
	return &openConfiggRPCClient{cc}
}

func (c *openConfiggRPCClient) GetModels(ctx context.Context, in *GetModelsInput, opts ...grpc.CallOption) (*GetModelsOutput, error) {
	out := new(GetModelsOutput)
	err := grpc.Invoke(ctx, "/IOSXRExtensibleManagabilityService.OpenConfiggRPC/GetModels", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for OpenConfiggRPC service

type OpenConfiggRPCServer interface {
	// get-models rpc implementation per
	// github.com/openconfig/public/blob/master/release/models/rpc/openconfig-rpc.yang
	GetModels(context.Context, *GetModelsInput) (*GetModelsOutput, error)
}

func RegisterOpenConfiggRPCServer(s *grpc.Server, srv OpenConfiggRPCServer) {
	s.RegisterService(&_OpenConfiggRPC_serviceDesc, srv)
}

func _OpenConfiggRPC_GetModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelsInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenConfiggRPCServer).GetModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IOSXRExtensibleManagabilityService.OpenConfiggRPC/GetModels",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenConfiggRPCServer).GetModels(ctx, req.(*GetModelsInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _OpenConfiggRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "IOSXRExtensibleManagabilityService.OpenConfiggRPC",
	HandlerType: (*OpenConfiggRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetModels",
			Handler:    _OpenConfiggRPC_GetModels_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("ems_grpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1414 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x58, 0x5b, 0x8f, 0xdb, 0x44,
	0x14, 0xae, 0xe3, 0xbd, 0xe5, 0xe4, 0xd2, 0x74, 0x28, 0xb0, 0x04, 0x84, 0x2a, 0x0b, 0x55, 0xd5,
	0x4a, 0xa4, 0x65, 0xdb, 0x02, 0x12, 0x02, 0x91, 0x26, 0xee, 0xd6, 0x65, 0x63, 0xa7, 0xe3, 0xa4,
	0x50, 0x09, 0x08, 0xde, 0x64, 0x9a, 0x1a, 0x12, 0xdb, 0xb5, 0xbd, 0x4b, 0xf7, 0x81, 0xcb, 0x03,
	0x48, 0xf0, 0xca, 0xcf, 0x81, 0x17, 0xc4, 0x0b, 0x7f, 0x8b, 0x99, 0xf1, 0xf8, 0xb6, 0x6d, 0xb2,
	0x4e, 0x4b, 0xf7, 0x61, 0xb5, 0x73, 0x8e, 0xe7, 0x7c, 0xe7, 0x3a, 0x33, 0xe7, 0x04, 0xea, 0x64,
	0x1e, 0x8c, 0xa6, 0xbe, 0x37, 0x6e, 0x79, 0xbe, 0x1b, 0xba, 0x48, 0xd1, 0x0c, 0xf3, 0x0b, 0xac,
	0x3e, 0x09, 0x89, 0x13, 0xd8, 0x07, 0x33, 0xd2, 0xb3, 0x1c, 0x6b, 0x6a, 0x1d, 0xd8, 0x33, 0x3b,
	0x3c, 0x36, 0x89, 0x7f, 0x64, 0x8f, 0x89, 0xa2, 0x41, 0xad, 0xe3, 0x3a, 0x0f, 0xed, 0xe9, 0x1e,
	0x09, 0xdb, 0xfe, 0x34, 0x40, 0x17, 0x61, 0x1d, 0x93, 0xc7, 0xda, 0x64, 0x5b, 0xba, 0x24, 0x5d,
	0x91, 0xf1, 0xba, 0xcf, 0x08, 0xa4, 0x40, 0xf5, 0xd8, 0x72, 0xa6, 0x9e, 0x15, 0x3e, 0xfa, 0x36,
	0x70, 0x9d, 0xed, 0x12, 0xfd, 0x58, 0xc6, 0x39, 0x9e, 0xf2, 0x0d, 0xd4, 0x13, 0x28, 0x4c, 0xbc,
	0xd9, 0x31, 0x6a, 0xc2, 0x16, 0x26, 0x41, 0x16, 0x6e, 0xcb, 0x17, 0x34, 0xfb, 0xc6, 0xa4, 0x33,
	0x68, 0x09, 0x8d, 0x5e, 0x83, 0x0d, 0xe2, 0xfb, 0xae, 0x1f, 0x6c, 0xcb, 0xfc, 0x8b, 0xa0, 0x94,
	0x3d, 0xa8, 0x50, 0x6c, 0xc3, 0x23, 0xfe, 0x0b, 0x9a, 0xfa, 0x35, 0x54, 0x05, 0xd0, 0xcb, 0x31,
	0xf4, 0x17, 0x09, 0x20, 0x8a, 0xc5, 0x12, 0x43, 0x97, 0x01, 0xbf, 0x05, 0x65, 0x2e, 0xef, 0xcf,
	0xc9, 0x84, 0x63, 0x6f, 0xe1, 0xf2, 0x38, 0x66, 0xa0, 0xcb, 0x22, 0xd2, 0xfe, 0x7c, 0x60, 0xcf,
	0x89, 0x7b, 0x18, 0x6e, 0xaf, 0xd1, 0x2d, 0x35, 0x5c, 0x1f, 0xe7, 0xb8, 0xca, 0x57, 0x50, 0x89,
	0xac, 0x38, 0xdd, 0xcb, 0xd4, 0x93, 0x52, 0xd6, 0x13, 0x26, 0xd3, 0x71, 0xe7, 0x73, 0x3b, 0xd4,
	0xba, 0xdc, 0x8e, 0x1a, 0xde, 0x1a, 0x0b, 0x5a, 0xf9, 0x81, 0xd6, 0xce, 0xcc, 0x3e, 0xd5, 0xcf,
	0x06, 0xc8, 0xe3, 0x99, 0x2d, 0x70, 0xd9, 0xf2, 0x7f, 0xf2, 0x8e, 0xd5, 0x5b, 0xac, 0xfe, 0xe5,
	0x38, 0xf8, 0x39, 0x5c, 0x88, 0xbe, 0x31, 0x78, 0x6b, 0x4c, 0x56, 0x72, 0x32, 0x9b, 0x5e, 0x39,
	0x9f, 0x5e, 0xe5, 0x0e, 0xa0, 0x1c, 0xf0, 0x73, 0x9b, 0xaf, 0x7c, 0xc4, 0x42, 0xc9, 0x90, 0x7a,
	0xc1, 0x94, 0x99, 0x36, 0xb3, 0x0e, 0xc8, 0x8c, 0x4b, 0x97, 0x71, 0x44, 0xa0, 0x6d, 0xd8, 0x64,
	0x1e, 0x11, 0x27, 0x14, 0xb2, 0x31, 0xa9, 0x7c, 0xc2, 0xaa, 0x94, 0x09, 0x2f, 0xaf, 0xd2, 0x24,
	0x3e, 0xa5, 0x13, 0xf1, 0x69, 0xb3, 0xfa, 0x8a, 0xdd, 0x78, 0x3e, 0xfb, 0x77, 0x00, 0x75, 0xed,
	0x60, 0x6c, 0xf9, 0x93, 0xce, 0x23, 0x1a, 0x1d, 0x12, 0x2c, 0x36, 0x85, 0xde, 0x55, 0xaf, 0xe4,
	0xf7, 0x3e, 0xbf, 0xda, 0x9b, 0x50, 0x31, 0x1f, 0xb9, 0xdf, 0x77, 0xe6, 0x93, 0x55, 0x72, 0x4a,
	0xef, 0x8d, 0x86, 0x10, 0x1b, 0x90, 0x27, 0xc5, 0xbc, 0xa6, 0x95, 0xea, 0x1d, 0xc6, 0x91, 0x17,
	0xd4, 0xc2, 0x7b, 0xe3, 0x61, 0x82, 0x7f, 0xd7, 0x34, 0xf4, 0xd3, 0xf1, 0xdf, 0x06, 0x60, 0xf5,
	0x94, 0xd3, 0x91, 0xe1, 0x2c, 0xd4, 0x73, 0x19, 0xe0, 0x9e, 0x61, 0xf6, 0x2c, 0xff, 0x3b, 0xdb,
	0x99, 0xb2, 0x02, 0x99, 0x47, 0x4b, 0xae, 0xa0, 0x86, 0x63, 0x52, 0xf9, 0x47, 0xa2, 0x67, 0xcc,
	0x27, 0x56, 0x48, 0xcc, 0xc3, 0x83, 0x25, 0xa9, 0xe1, 0x8a, 0x9c, 0xb1, 0x3b, 0x21, 0xdc, 0x08,
	0x19, 0x0b, 0x8a, 0x19, 0x1f, 0x1c, 0x1e, 0xd8, 0x93, 0x20, 0xf4, 0xe3, 0x43, 0x10, 0xd3, 0xe8,
	0x53, 0x90, 0x1f, 0xbb, 0x01, 0x3f, 0xdc, 0x95, 0xdd, 0x56, 0xeb, 0xf4, 0xc7, 0xaa, 0x95, 0xda,
	0x8c, 0x99, 0x28, 0x7a, 0x07, 0x6a, 0xcc, 0xae, 0xb1, 0x6f, 0x7b, 0xa1, 0xed, 0x3a, 0xc1, 0xf6,
	0xfa, 0x25, 0x99, 0xaa, 0xa8, 0x05, 0x59, 0xa6, 0x72, 0x17, 0xea, 0xed, 0x31, 0x5b, 0xb2, 0x98,
	0xbe, 0xe0, 0xc3, 0x61, 0xc1, 0xf9, 0x14, 0xeb, 0xe5, 0xbc, 0x1d, 0x0f, 0xe0, 0x7c, 0x1a, 0xf2,
	0xd3, 0x55, 0x20, 0x58, 0x9b, 0x58, 0xa1, 0xc5, 0xe1, 0xab, 0x98, 0xaf, 0x17, 0x42, 0xff, 0x51,
	0x82, 0x3a, 0x7d, 0xf7, 0x7a, 0x34, 0x33, 0xb3, 0x40, 0x73, 0x58, 0x85, 0xd0, 0xab, 0x98, 0x7a,
	0x7f, 0x48, 0x82, 0x50, 0x60, 0xaf, 0xe1, 0x94, 0xc1, 0xc0, 0x1d, 0x6b, 0x4e, 0x84, 0xed, 0x7c,
	0xcd, 0x24, 0xd8, 0xff, 0xc0, 0xa3, 0xf7, 0x96, 0xc0, 0x4f, 0x19, 0xac, 0x96, 0x8e, 0x88, 0x1f,
	0xd0, 0x08, 0xf1, 0xc4, 0xd2, 0xcb, 0x46, 0x90, 0x68, 0x0a, 0x15, 0x01, 0x3c, 0x38, 0xf6, 0x08,
	0x4d, 0x95, 0x74, 0xa5, 0xbe, 0xab, 0x16, 0x49, 0x7b, 0xde, 0xe4, 0x56, 0xcf, 0xe8, 0xee, 0xab,
	0x23, 0xac, 0xde, 0x1b, 0xaa, 0xe6, 0x60, 0x34, 0x78, 0xd0, 0x57, 0x71, 0x16, 0x59, 0x79, 0x17,
	0xd0, 0xd3, 0x5b, 0x50, 0x05, 0x36, 0xcd, 0x61, 0xaf, 0xd7, 0xc6, 0x0f, 0x1a, 0xe7, 0x10, 0xc0,
	0x46, 0x57, 0x1d, 0xb4, 0xb5, 0xfd, 0x86, 0xa4, 0xfc, 0x2d, 0xc3, 0xf9, 0x44, 0x83, 0x11, 0x9d,
	0x9b, 0xe5, 0x51, 0x19, 0xc2, 0xc6, 0x9c, 0xef, 0xa6, 0x71, 0x91, 0x69, 0xed, 0x7e, 0xbc, 0x92,
	0x13, 0x91, 0x8a, 0x16, 0x27, 0x34, 0xe7, 0xa1, 0x8b, 0x05, 0x18, 0xfa, 0x12, 0xaa, 0x34, 0xab,
	0x1e, 0x2d, 0x59, 0xd2, 0x61, 0x27, 0x49, 0xe6, 0x11, 0xfa, 0xb0, 0x08, 0xb8, 0xd1, 0x19, 0xe1,
	0x3e, 0xfd, 0x53, 0xcd, 0xbe, 0xa1, 0x9b, 0x6a, 0x14, 0x94, 0x1c, 0x1a, 0xbb, 0xcc, 0xe6, 0xc1,
	0x54, 0x24, 0x85, 0x2d, 0x9b, 0xff, 0x4a, 0x50, 0x4e, 0xac, 0x48, 0x52, 0x2d, 0x2d, 0x4a, 0x75,
	0x69, 0x49, 0xaa, 0xe5, 0x7c, 0xaa, 0xfb, 0x50, 0xe6, 0x3e, 0xf1, 0x44, 0xaf, 0x71, 0x37, 0x76,
	0x0b, 0xc5, 0x48, 0x1d, 0x8c, 0x68, 0xea, 0xd4, 0xfd, 0xc8, 0x81, 0x14, 0x84, 0x59, 0xc2, 0x89,
	0x2e, 0x2b, 0xf5, 0xf5, 0xc8, 0x92, 0x84, 0xa1, 0x74, 0xa1, 0x41, 0xc3, 0xdb, 0x67, 0x4d, 0xef,
	0x6d, 0x7b, 0x96, 0x3c, 0xd3, 0xfe, 0xc2, 0x9e, 0xab, 0x4f, 0xcf, 0x73, 0xf6, 0x40, 0x32, 0x5a,
	0x21, 0x70, 0x21, 0x8b, 0x12, 0x1d, 0xbd, 0x67, 0xc3, 0xd0, 0xab, 0x82, 0xb7, 0xd8, 0xb4, 0xf9,
	0x08, 0xd3, 0x77, 0x35, 0xc7, 0x5b, 0x74, 0x08, 0x77, 0xae, 0x43, 0x35, 0x7e, 0x34, 0x83, 0xc3,
	0x59, 0xc8, 0x6a, 0xb1, 0x73, 0xa7, 0xad, 0xef, 0xa9, 0xb4, 0x2e, 0x6b, 0x50, 0xd6, 0x8d, 0x91,
	0x20, 0x25, 0xb4, 0x05, 0x6b, 0xb7, 0x59, 0x91, 0x96, 0x76, 0xfe, 0x92, 0xe0, 0xe2, 0xb3, 0x92,
	0x8c, 0x36, 0xa0, 0x64, 0x7c, 0x46, 0x25, 0x37, 0x41, 0xd6, 0xe9, 0x42, 0xa2, 0x06, 0x37, 0x86,
	0xba, 0x39, 0xec, 0xf7, 0x0d, 0x3c, 0x50, 0xbb, 0xa3, 0x7e, 0x7b, 0x70, 0xa7, 0x51, 0xa2, 0xd9,
	0xaf, 0x6a, 0xfa, 0xfd, 0xf6, 0xbe, 0x26, 0x38, 0x32, 0x7a, 0x03, 0x5e, 0x8d, 0x39, 0x1d, 0x43,
	0xbf, 0xad, 0xed, 0x0d, 0x71, 0x7b, 0xa0, 0x19, 0x7a, 0x63, 0x8d, 0x26, 0xf6, 0x62, 0x16, 0x42,
	0xd3, 0x07, 0x2a, 0xa6, 0x3b, 0x1b, 0xeb, 0x27, 0xbf, 0xa8, 0x7a, 0xc7, 0xe8, 0x6a, 0xfa, 0x5e,
	0x63, 0x03, 0xbd, 0x09, 0xaf, 0xc7, 0x70, 0xe6, 0xf0, 0x96, 0xd9, 0xc1, 0x5a, 0x9f, 0xa1, 0x8d,
	0xb4, 0x6e, 0x63, 0x73, 0x47, 0xa3, 0xd7, 0x4e, 0x2e, 0xb5, 0xcc, 0x69, 0x4a, 0x0d, 0xf7, 0x99,
	0xd3, 0xd4, 0xb6, 0xf6, 0x70, 0xaf, 0xa7, 0xea, 0x83, 0xc8, 0x00, 0x89, 0x85, 0xa1, 0xab, 0xde,
	0xd7, 0x22, 0xb2, 0xc4, 0x36, 0xdf, 0x1a, 0xea, 0xf4, 0x44, 0x37, 0xe4, 0xdd, 0x3f, 0x2b, 0x50,
	0x9f, 0xd2, 0x30, 0x44, 0x6d, 0x1f, 0xeb, 0xe0, 0xd1, 0x11, 0x94, 0x69, 0xde, 0x22, 0x06, 0x7a,
	0xaf, 0x48, 0x9d, 0xe5, 0x26, 0x9e, 0xe6, 0xee, 0x4a, 0x22, 0xbc, 0x2c, 0x94, 0x73, 0xd7, 0x24,
	0xe4, 0x41, 0xa5, 0x47, 0xfc, 0x29, 0x11, 0x9a, 0x5b, 0xc5, 0x61, 0xb8, 0xda, 0xab, 0xc5, 0xf7,
	0x0b, 0x9d, 0xe8, 0x31, 0x54, 0xbb, 0x64, 0x46, 0xc2, 0xb3, 0x55, 0x89, 0xc9, 0xdc, 0x3d, 0x3a,
	0x43, 0x95, 0x3e, 0xd4, 0x44, 0x5b, 0x7c, 0x76, 0x3a, 0x43, 0xda, 0x46, 0xc7, 0xb3, 0x44, 0xc1,
	0x1a, 0xca, 0x4e, 0x3e, 0x05, 0x6b, 0x28, 0x37, 0xad, 0x50, 0xad, 0x3f, 0x4b, 0x6c, 0xfa, 0xce,
	0xcc, 0x01, 0xe8, 0x66, 0x31, 0xd3, 0x4f, 0xcc, 0x24, 0xcd, 0xf7, 0x57, 0x16, 0xcb, 0xe4, 0x37,
	0xe2, 0xaf, 0x16, 0xeb, 0x78, 0x68, 0x28, 0x1a, 0xeb, 0x64, 0x48, 0xa0, 0x2a, 0x7f, 0xa7, 0x77,
	0x59, 0xa4, 0x2d, 0xdf, 0xcd, 0xa3, 0x42, 0x5e, 0x3c, 0x3d, 0x2d, 0x34, 0x3f, 0x58, 0x5d, 0x2e,
	0xb6, 0xc5, 0x83, 0x4d, 0xf1, 0x43, 0x00, 0xba, 0x5a, 0xf0, 0x15, 0x8f, 0x7f, 0x7e, 0x68, 0x5e,
	0x5b, 0x41, 0x20, 0xbd, 0x35, 0x8e, 0xe9, 0xcc, 0x95, 0xb4, 0x77, 0xa8, 0x58, 0xdd, 0xe4, 0x3a,
	0xf0, 0xe6, 0xf5, 0xd5, 0x64, 0x52, 0xd5, 0x3f, 0xf1, 0x5f, 0x3d, 0x92, 0x07, 0x0e, 0xdd, 0x28,
	0xe8, 0x40, 0xee, 0x61, 0x6d, 0xde, 0x5c, 0x55, 0x2a, 0x31, 0x60, 0xf7, 0x57, 0x19, 0xb6, 0xd8,
	0xe5, 0xad, 0x3e, 0x21, 0x63, 0xf4, 0x23, 0x5c, 0xc8, 0xcc, 0x52, 0xa2, 0xf1, 0x2a, 0x94, 0x84,
	0xcc, 0xe4, 0xd6, 0xbc, 0xb1, 0x82, 0x40, 0x32, 0xb3, 0xf1, 0x68, 0xa4, 0xfa, 0x59, 0x2f, 0x7f,
	0x16, 0xfa, 0x93, 0x99, 0x21, 0x2e, 0x84, 0x74, 0x94, 0x28, 0x56, 0x08, 0xf9, 0x31, 0xa6, 0x58,
	0x21, 0x9c, 0x18, 0x57, 0x78, 0x1e, 0x7e, 0xa3, 0x63, 0x1d, 0xad, 0x4a, 0x27, 0x3a, 0x85, 0x2c,
	0x23, 0xe2, 0x11, 0x8d, 0x3a, 0xd4, 0x62, 0xc6, 0xe4, 0xbb, 0xf2, 0x62, 0xc6, 0x9c, 0x68, 0x82,
	0x95, 0x73, 0x07, 0x1b, 0xbc, 0x67, 0xba, 0xfe, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf5, 0x21,
	0x8f, 0x0a, 0xbc, 0x14, 0x00, 0x00,
}
